import json, re, collections
import os
HERE=os.path.dirname(os.path.abspath(__file__))
R=HERE+'/'; OUT=os.path.join(HERE,'..','public','hub')+'/'
L=lambda f: json.load(open(R+f))
# Corrections from the second verification pass (every crisis/mental number re-opened on its source page, Sept 2026).
PATCH={
  'rs-sos-lazalazarevic': {'phone': '011 7777 000; 0800 309 309 (Find A Helpline)', 'via_directory': True},
  'us-csc': {'phone': 'CSC-867-5309 (272-867-5309) / 888-793-9355 (toll-free)'},
  'cn-bpcric': {'phone': '010-82951332 (mobile) / 800-810-1117 (landline)'},
  'lv-skalbes-crisis': {'hours': None}, 'ng-surpin': {'hours': None}, 'hr-hzjz-counselling': {'hours': None},
  'sk-lpr': {'hours': 'every day'},
  'co-liga': {'phone': '3242536269 (WhatsApp)'}, 'br-oncoguia': {'phone': '+55 11 94242-8536 (WhatsApp)'},
  'ch-krebstelefon': {'name': 'Krebsliga – KrebsInfo (Krebstelefon)'},
  'no-kreftlinjen': {'name': 'Kreftforeningen – rådgivningstjeneste (Kreftlinjen)'},
}
DROP={'ua-lastrada','am-sacc','am-women-support','ge-116006','mk-sos-domestic-violence','md-lastrada-trust','bg-animus','bg-demetra-dv','lv-marta','mk-lastrada-sos','lv-bkus','ro-little-people'}
countries={}
order=[]
for f in ['patients_east.json','patients_west.json','patients_world.json']:
    for c in L(f)['countries']:
        c=dict(c); c.pop('needs_research',None)
        countries[c['code']]=c; order.append(c['code'])
for c in L('patients_east_fill.json')['countries']:
    base=countries[c['code']]
    if not base.get('emergency'):
        base['emergency']=c['emergency']; base['emergency_source']=c.get('emergency_source')
    have={e['id'] for e in base['entries']}
    base['entries']+= [e for e in c['entries'] if e['id'] not in have]
KEEP=['id','name','name_local','url','kind','phone','hours','langs','free','desc_en','desc_ru','source','via_directory']
out=[]
for code in order:
    c=countries[code]
    ents=[{k:v for k,v in {**e, **PATCH.get(e['id'],{})}.items() if k in KEEP and v is not None} for e in c['entries'] if e['id'] not in DROP]
    for e in ents:
        if not e.get('url'): e['url']=e.get('source')
    ents=[e for e in ents if e.get('url')]
    if not ents: continue
    out.append({'code':code,'name_en':c['name_en'],'name_ru':c['name_ru'],'lat':c['lat'],'lng':c['lng'],
                'emergency':c.get('emergency') or [],'emergency_source':c.get('emergency_source'),'entries':ents})
intl=[{k:e.get(k) for k in KEEP if e.get(k) is not None} for e in L('patients_intl.json')['entries']]
reading=L('patients_reading.json')
pat={'checked':'2026-09','countries':out,'intl':intl,'reading':reading['items'],'topics':reading['topics']}
json.dump(pat,open(OUT+'patients.json','w'),ensure_ascii=False,separators=(',',':'))
papers=L('papers.json'); paths=L('papers_learning_paths.json'); tb=L('toolbox.json'); faq=L('faq.json')
ids=[p['id'] for p in papers]+[t['id'] for t in tb]
dup=[k for k,v in collections.Counter(ids).items() if v>1]
assert not dup, dup
res={'checked':'2026-09','papers':papers,'paths':paths,'toolbox':tb,'faq':faq}
json.dump(res,open(OUT+'research.json','w'),ensure_ascii=False,separators=(',',':'))
n=sum(len(c['entries']) for c in out)
print('countries',len(out),'entries',n,'intl',len(intl),'reading',len(reading['items']),'topics',len(reading['topics']))
print('papers',len(papers),'toolbox',len(tb),'faq',len(faq),'paths',len(paths))
print([ (c['code'],len(c['entries'])) for c in out])
kinds=collections.Counter(e['kind'] for c in out for e in c['entries']); print(kinds)
print(collections.Counter(t['cat'] for t in tb))
import os; print({f:os.path.getsize(OUT+f) for f in os.listdir(OUT)})
stats={'papers':len(papers),'tools':len(tb),'paths':len(paths),'countries':len(out),'services':n+len(intl),'reading':len(reading['items'])}
import os; os.makedirs(os.path.join(HERE,'..','src','data'),exist_ok=True)
open(os.path.join(HERE,'..','src','data','hubStats.js'),'w').write('// generated by research/merge.py — counts shown on the story page\nexport const HUB_STATS = '+json.dumps(stats)+';\n')
print(stats)
